name: run-analysis

on:
  workflow_dispatch:

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run analyze.py
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: python analyze.py

    - name: Commit analysis.txt
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add analysis.txt
        git commit -m "Update analysis" || echo "No changes to commit"
        git push
